name: Context testing
on: push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest  # ubuntu 최신버전에서 실행
    steps:
      - uses: actions/checkout@v3 # post branch 의 파일들 가져오기
        with: 
          ref: posts

      - name: Set up Python # Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          
      - name: Run
        run: |
          python test.py
